# Compose fileのバージョン指定
version: '3'
# どんなコンテナを立ち上げるか
services:
 # laravelを動かすコンテナ
 app:
   # どのポートを開いて繋ぐか。下記はコンテナの80番ポートを開いて、ホストの8000番につなぐ
   ports:
     - "8000:80"
   build: ./docker/app
   # コンテナの名前を指定
   container_name: laravel_app
   volumes:
     - ./src:/var/www/html
 # MySQLコンテナ
 db:
   image: mysql:8.0
   container_name: laravel_db
   environment:
     MYSQL_ROOT_PASSWORD: rootpw
     MYSQL_DATABASE: laravel_db
     MYSQL_USER: user
     MYSQL_PASSWORD: userpw
     TZ: 'Asia/Tokyo'
   # 起動時のコマンド
   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
   volumes:
     - ./docker/db/data:/var/lib/mysql
     - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
   ports:
     - 3306:3306
# node.jsのコンテナ
 node:
    image: node:12.8
    volumes:
        - ./src:/var/www/html
    working_dir: /var/www/html
     